#include <stdio.h>


int main(){

/*If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

  Find the sum of all the multiples of 3 or 5 below 1000.*/
  int i;
  int sum = 0;
  for (i = 1; i < 1000; i++)
    if (i % 3 == 0 || i % 5 == 0)
      sum += i;
  printf("%d\n", sum);

  /*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

  int a = 1;
  int b = 2;
  int summ = 2;
  while (b < 4000000){
    int next = a + b;
    if (next % 2 == 0)
      summ += next;
    a = b;
    b = next;
  }
  printf("%d\n", summ);

  
  
}
